name: Run-test-on-push
on: [push]
jobs:
  run-tests:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Check out our code
        uses: actions/checkout@v3


      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
